### ISSUE TITLE
is single precision required?

### ISSUE THREAD

**Issue by dominicrufa** [openmm/openmm-ml#10]
@peastman , in looking at the `anipotential.py`, i noticed that you are hardcoding [single precision](https://github.com/openmm/openmm-ml/commit/438862eb9b51087045ebd7fffb7be90f664c56a3). is this a requirement/will it cause artifacts if I am using mixed precision on a GPU?

**Comment by peastman** [comment]
That's because the model uses single precision.  Possibly there's a way to get TorchANI to build a double precision model.  I haven't looked into that.

In mixed precision mode, we generally compute all forces in single precision, so this is consistent with how that usually works.
