### ISSUE TITLE
How do we select whether we want to use entire ANI ensemble or just one model?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm-ml#37]
Can we document how we select whether we use the entire ANI ensemble or just one model?
Presumably, this would be handled by one of the `**args` passed to [`ANIPotentialImpl`](https://github.com/openmm/openmm-ml/blob/main/openmmml/models/anipotential.py#L43-L68), but I couldn't figure out if we actually support this or, if we do, what the args should be.

**Comment by peastman** [comment]
I don't think we currently have an option to use just one model.  It uses the full ensemble from `torchani`.

https://github.com/openmm/openmm-ml/blob/5b577c2586232d3ac6f41de064d3290619b2a8aa/openmmml/models/anipotential.py#L77-L80

**Comment by peastman** [comment]
This would be a useful feature to add.  I can see a couple of options for the API.  One would be to use a different model name, for example `'ani2x-single` to get a single model version.  Alternatively we could accept an additional argument such as `modelIndex` to specify the index of a single model to use.  If the argument was omitted, you would get the full ensemble.

Any preferences between these?

**Comment by jchodera** [comment]
I think @dominicrufa needs this feature for his own work, so I'd be thrilled if we added it!

I like the `modelIndex` optional argument, where (for ML models that have ensembles) the user can specify one of:
* `None` (default) : use all models from the ensemble
* `int` : use the specified model index
* iterable of `int`: use the specified subset of models

We might also want to allow users to specify the force index to be assigned to the expensive ML part, since I imagine a use case folks will want to explore is multiple timestep integrators that use a subset of models at different parts in the integrator cycle, or for other Monte Carlo or reweighting purposes.

**Comment by peastman** [comment]
> iterable of int: use the specified subset of models

I don't think there's any way to do that using the torchani public API.  I could probably hack something together, but it would require using an internal class (BuiltinEnsemble) that they specifically warn you not to depend on.  The only supported cases are the full ensemble, and a single model out of the ensemble.

**Comment by jchodera** [comment]
OK.
