### ISSUE TITLE
adding the torchani `EnergyShifter` to subtract the self energies of molecules

### ISSUE THREAD

**Issue by dominicrufa** [openmm/openmm-ml#44]
would it be possible to add [`EnergyShifter`](https://github.com/aiqm/torchani/blob/ef834586e38015ddc066d938734b5f53fc741c2c/torchani/utils.py#L139) to the current `torchani` workflow in order to remove the self energy of molecules treated with ML? Energies at present are very large/small and there is concern that this could leading to numerical instability with finite precision.

**Comment by dominicrufa** [comment]
@peastman, it's not obvious to me how to place it in [`anipotential`](https://github.com/openmm/openmm-ml/blob/main/openmmml/models/anipotential.py). the documentation [here](https://github.com/aiqm/torchani/blob/ef834586e38015ddc066d938734b5f53fc741c2c/torchani/utils.py#L189-L190) seems to suggest that the `EnergyShifter` adds another multiple of the self interaction energy onto the pre-computed energy, unless i am reading it incorrectly.

**Comment by peastman** [comment]
I think it's already included:

```python
>>> model = torchani.models.ANI1ccx(periodic_table_index=True)
>>> print(model.energy_shifter.self_energies)
tensor([ -0.5992, -38.0375, -54.6745, -75.1604], dtype=torch.float64)

```
