### ISSUE TITLE
Errors while installing OpenMM 8.0

### ISSUE THREAD

**Issue by saratk1** [openmm/openmm-ml#45]
Hi openmm-ml developers,
I was trying to install the beta release of OpenMM 8.0 and I created a conda environment with compatible versions of all the packages as described [here](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=15133&p=0&start=0&view=) (`conda env create mmh/openmm-8-beta-linux`). When trying to run the openmm-ml tests (`TestMLPotential.py`) I got several error messages, eg. 

`E       RuntimeError: Tried to instantiate class 'cuaev.CuaevComputer', but it does not exist! Ensure that it is registered via torch::class_`

I also attach the full error log here: [error_log.txt](https://github.com/openmm/openmm-ml/files/10175081/error_log.txt)
Is there something I can do to fix this?

**Comment by JohannesKarwou** [comment]
I get the same error when trying to install the new release...

**Comment by peastman** [comment]
This looks to me like an issue with incompatible libraries in different packages.  The error log contains the exception

```
E       ImportError: /data/shared/software/conda_environment/envs/endstate_test_2/lib/python3.10/site-packages/torchani/cuaev.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops4full4callEN3c108ArrayRefIlEERKNS2_6ScalarENS2_8optionalINS2_10ScalarTypeEEENS8_INS2_6LayoutEEENS8_INS2_6DeviceEEENS8_IbEE
```

Can you post the output of `conda list`?

**Comment by saratk1** [comment]
Thanks for the response! The installation worked with mamba.
