### ISSUE TITLE
OpenMM-ML 1.1

### ISSUE THREAD

**Issue by raimis** [openmm/openmm-ml#57]
A bug (#55) had been fixed (#56). It is time for the next release.

Related issues: there are several releases (https://anaconda.org/conda-forge/openmm-ml/files) but no corresponding release notes or even tags in this repo.

Ping: @peastman @mikemhenry

**Comment by peastman** [comment]
I created a release corresponding to 1.0, and I opened a PR at https://github.com/conda-forge/openmm-ml-feedstock/pull/8 to build packages for 1.1.

**Comment by mikemhenry** [comment]
Released :tada:

**Comment by peastman** [comment]
And I've created the github release.  Thanks!

**Comment by raimis** [comment]
Thanks @peastman
