### ISSUE TITLE
Challenges with Hybrid OpenMM-ML Simulation: Unable to Parametrize Ligand with Force Field

### ISSUE THREAD

**Issue by raurauraul** [openmm/openmm-ml#66]
Context: As a biology student from Brazil, I'm not typically involved in programming but rather in using bioinformatics tools. I am seeking to learn how to conduct hybrid simulations with ligands/proteins using ANI in OpenMM-ML, where these ligands can be carbohydrates or small molecules. The challenge I face is that to apply ANI to the ligand, the entire system must be parametrized with a classical force field, which has been problematic. Additionally, the PDB files I use are complexes of the protein with the ligand. I would greatly appreciate guidance on how to properly set up the force field for the ligand in such simulations.

### Problem Description
I am attempting to conduct a hybrid simulation using OpenMM, where the ligand is treated with the ANI potential (through OpenMM-ML) and the protein with a classical force field (I've tried both CHARMM and AMBER). However, I am consistently encountering issues in parametrizing the force field for the ligand. Whether it's a small molecule or a carbohydrate, the force field (including GAFF, Glycam, Amber or Charmm) fails to recognize the ligand.

### Approaches Attempted
1. **Using GAFF with OpenFF Toolkit**: I tried generating templates for the ligand using GAFF and the OpenFF Toolkit, but faced issues with `ValueError: No template found for residue 1 (LIG)`.
code: molecule = Molecule.from_file('/home/user/Documentos/ligand.sdf', file_format='sdf')
gaff = GAFFTemplateGenerator(molecules=molecule)
forcefield = ForceField('amber14-all.xml','amber/tip3p_HFE_multivalent.xml')
forcefield.registerTemplateGenerator(gaff.generator)
pdbfile = PDBFile('/home/user/Documentos/test.pdb')
system = forcefield.createSystem(pdbfile.topology,  nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=HBonds)

-The ligand.sdf file is the .sdf version of the ligand alone from the test.pdb complex (which has ligand + protein).

2. **Using Classical Force Fields (CHARMM and AMBER)**: I attempted to create systems with classical force fields for the protein but kept running into the same template issue for the ligand.

3. **Using GLYCAM**: Parametrizing carbohydrates for the GLYCAM force field in PDB files has been challenging. Modifying the file manually to suit GLYCAM seems intricate, and I haven't found a tool that simplifies this process. The GLYCAM force field doesn't recognize the carbohydrates in the PDB files I've used.

My goal is not to run a specific system in OpenMM-ML (though I was initially advised to try with the PDB complex: 3QUD), but to learn how to perform hybrid simulations of ligands/proteins with ANI. Any guidance on how to properly parametrize the entire system with a classical force field before applying ANI to the ligand, and how to overcome the current challenges, would be immensely helpful.

My system: Ubuntu 22.04
All packages installed in a conda environment with python 3.10, including: cudatoolkit 11.8.0 ; pytorch 2.0.0 with cuda support; openmm 8.0.0; openmm-ml 1.1; openmm-setup 1.3; openmm-torch 1.4; openmmforcefields 0.12.0; torchani 2.2.3

**Comment by peastman** [comment]
The GAFFTemplateGenerator ought to work.  Make sure the molecule in the SDF file is really identical to the one in the PDB.  Also make sure the description in the PDB file is correct.  It needs to include CONECT records for all the bonds, and it should specify elements for all the atoms.  Also make sure every atom within the ligand has a unique name.

If it's none of those things, can you post your files here?

**Comment by peastman** [comment]
Closing since the poster never replied.
