### ISSUE TITLE
Create 1.2 release

### ISSUE THREAD

**Issue by peastman** [openmm/openmm-ml#82]
It's been quite a while since the last official release, and there have been some important changes since then, such as support for MACE models.  Shall we create a new release?  Are there any pending changes that really need to be done first?

**Comment by JMorado** [comment]
I think it makes sense to create a new release that includes the latest changes!

As for pending changes, the only one on my side is the support for models generated through NequIP/Allegro. Although the implementation seems to be stable, I think it's okay not to merge it right now for further testing and only include it in future releases.
