### ISSUE TITLE
Installation with latest torch

### ISSUE THREAD

**Issue by shenoynikhil** [openmm/openmm-ml#85]
Installing this package with recent versions of torch results in package conflicts. I am using the following yml file to install my environment. 
```
name: custom_env
channels:
  - conda-forge
  - pytorch
  - nvidia
  - pyg

dependencies:
  # standard stuff
  - python >=3.8
  - pip

  # ML
  - e3nn
  - pytorch::pytorch
  - pytorch::pytorch-cuda==12.1
  - pyg::pyg

  # MD
  - openmm
  - openmm-ml
  - openmm-torch
```
I think it comes from `torchani`'s incompatibility with recent torch versions. Any suggestions on how this could be potentially fixed?

**Comment by JMorado** [comment]
Hi @shenoynikhil,
What happens if you use the following YAML file:

```
name: custom_env
channels:
  - conda-forge
  - pyg

dependencies:
  # standard stuff
  - python >=3.8
  - pip
  - cudatoolkit

  # ML
  - e3nn
  - pytorch
  - pyg

  # MD
  - openmm
  - openmm-ml
  - openmm-torch
```

Assuming you're on x86_64, this resolves to the latest packages on my end.

**Comment by JMorado** [comment]
It seems the package causing the conflicts was PyG. It works fine if you install it afterwards via pip, as described [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).

**Comment by peastman** [comment]
Combining packages from conda-forge with any other channel often doesn't work correctly.

**Comment by shenoynikhil** [comment]
@JMorado That seems to resolve the issue!
