### ISSUE TITLE
Issues with serializing the mixedSystem

### ISSUE THREAD

**Issue by kimjc95** [openmm/openmm-ml#87]
Hi, I am trying to implement OpenMM-ML in my code to simulate systems made from non-standard residues.
I am getting the following error while serializing the mixedSystem.

Is there something I'm missing?
Thanks in advance.
 
```
Using MACE-OFF23 MODEL for MACECalculator with /root/.cache/mace/MACE-OFF23_small.model
/usr/local/lib/python3.10/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
---------------------------------------------------------------------------
OpenMMException                           Traceback (most recent call last)
[<ipython-input-24-ca25b3076a95>](https://localhost:8080/#) in <cell line: 184>()
    184 if final_system is not None:
    185     with open('system.xml', 'w') as f:
--> 186         f.write(XmlSerializer.serialize(final_system))
    187 
    188     print("Creating simulation...", end='')

1 frames
[/usr/local/lib/python3.10/site-packages/openmm/openmm.py](https://localhost:8080/#) in serializeSystem(object)
   6824         Get the force field parameters for an interaction that should be calculated differently from others.
   6825 
-> 6826         Parameters
   6827         ----------
   6828         index : int

OpenMMException: There is no serialization proxy registered for type N11TorchPlugin10TorchForceE
```

**Comment by peastman** [comment]
I'm not sure what's going on.  I just tested serializing a TorchForce and it worked fine.  The serialization proxy for TorchForce is defined in the same library that TorchForce itself is in, so I don't see how you would get one without the other.  Perhaps there's an ABI incompatibility somewhere?  How did you install all the packages (OpenMM, OpenMM-Torch, PyTorch)?

**Comment by kimjc95** [comment]
I am writing my codes on Google Colaboratory notebook.
Installed OpenMM and OpenMM-torch via Mamba. PyTorch was already available on Colab environment.

**Comment by kimjc95** [comment]
nevermind...
Initially, I installed openmm and then installed openmm-ml afterwards.
When I downloaded openmm openmm-ml nnpops at once and it solved the problem.
